### PR TITLE
Include fixes to make reaper api doc parseable

### PR DESCRIPTION
**Pull request by AntoineBalaine**
Hello,

Reason I'm sending this is because I'm trying to re-use the parsing method sent by X-Raym that's contained in the reaper-vscode extension. I was getting failures when trying to parse, until I found out these three things.

I'm including these three line-changes to fix parseability:
1. at lign 8660, I was getting issues parsing nested quotes. That's a simple fixe using apostrophes instead.
2. at lign 40424, leaving the angled bracket unsurrounded by spaces was causing parsers to try to interpret that section as a tag.
3. lign 37010, I believe that's a mis-matched tag.

X-Raym's method: https://forum.cockos.com/showpost.php?p=2182879&postcount=295
VSCode extension's repo: https://github.com/GavinRay97/vscode-reascript-extension/

I'd love to target your dev branch instead of master for this PR, but I'm not sure which one it is. Please let me know and I'll change the target.

Regards,

Antoine

### CODE REVIEW

**Comment by mespotine** [comment]
Best is to document the issues in an issue, since I'm already working with a new dev-branch. Am I right to assume, that you refer to the Reaper Api-docs-file? -------- Ursprüngliche Nachricht --------Von: Antoine Balaine ***@***.***>Datum: So., 2. Juli 2023, 16:15An: Ultraschall/ultraschall-lua-api-for-reaper ***@***.***>Cc: Subscribed ***@***.***>Betreff: [Ultraschall/ultraschall-lua-api-for-reaper] Include fixes to make reaper api doc parseable (PR #20)Hello,
Reason I'm sending this is because I'm trying to re-use the parsing method sent by X-Raym that's contained in the reaper-vscode extension. I was getting failures when trying to parse, until I found out these three things.
I'm including these three line-changes to fix parseability:
at lign 8660, I was getting issues parsing nested quotes. That's a simple fixe using apostrophes instead.at lign 40424, leaving the angled bracket unsurrounded by spaces was causing parsers to try to interpret that section as a tag.lign 37010, I believe that's a mis-matched tag.
X-Raym's method: https://forum.cockos.com/showpost.php?p=2182879&postcount=295
VSCode extension's repo: https://github.com/GavinRay97/vscode-reascript-extension/
I'd love to target your dev branch instead of master for this PR, but I'm not sure which one it is. Please let me know and I'll change the target.
Regards,
Antoine



You can view, comment on, or merge this pull request online at:
  https://github.com/Ultraschall/ultraschall-lua-api-for-reaper/pull/20

Commit Summary
cf75382  Include fixes to make api doc parseable

File Changes  (1 file)

    M
    ultraschall_api/DocsSourcefiles/reaper-apidocs.USDocML
    (6)
  

Patch Links:
https://github.com/Ultraschall/ultraschall-lua-api-for-reaper/pull/20.patchhttps://github.com/Ultraschall/ultraschall-lua-api-for-reaper/pull/20.diff

**Comment by mespotine** [comment]
In addition: please don't use XRaym's method to parse the USDocML-file. Ultraschall-API has dedicated functions for this, that you can find listed here:

https://mespotin.uber.space/Ultraschall/US_Api_DOC.html#Reaper%20Docs

For instance, if you want to get the description for GetTrack, you use:
[https://mespotin.uber.space/Ultrasch...on_Description](https://mespotin.uber.space/Ultraschall/US_Api_DOC.html#Docs_GetReaperApiFunction_Description)


```
dofile(reaper.GetResourcePath().."/UserPlugins/ultraschall_api.lua")

Description = ultraschall.Docs_GetReaperApiFunction_Description("GetTrack")
```

To get all existing functionnames for Reaper's API, use Docs_GetAllReaperApiFunctionnames:

https://mespotin.uber.space/Ultraschall/US_Api_DOC.html#Docs_GetAllReaperApiFunctionnames

The dedicated functions also don't have the parsing problems.

I'll add one of your fixes anyways(the reval-typo) and release a hotfix-update for this.

**Comment by mespotine** [comment]
> I'll add one of your fixes anyways(the reval-typo) and release a hotfix-update for this.

Done

**Comment by AntoineBalaine** [comment]
Sounds good, thanks for including the change. I'll close the PR.

**Pull request closed without merging**
